// <auto-generated />
using System;
using GradingSystem.models;
using GradingSystem.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradingSystemConsole.Migrations
{
    [DbContext(typeof(GradingSystemContext))]
    partial class GradingSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GradingSystem.models.Cohort", b =>
                {
                    b.Property<int>("cohortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("cohortId");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("GradingSystem.models.Grade", b =>
                {
                    b.Property<int>("gradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("letterGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("numberGrade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("studentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("gradeId");

                    b.HasIndex("studentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("GradingSystem.models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cohortId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("studentId");

                    b.HasIndex("cohortId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GradingSystem.models.Grade", b =>
                {
                    b.HasOne("GradingSystem.models.Student", null)
                        .WithMany("grades")
                        .HasForeignKey("studentId");
                });

            modelBuilder.Entity("GradingSystem.models.Student", b =>
                {
                    b.HasOne("GradingSystem.models.Cohort", null)
                        .WithMany("students")
                        .HasForeignKey("cohortId");
                });

            modelBuilder.Entity("GradingSystem.models.Cohort", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("GradingSystem.models.Student", b =>
                {
                    b.Navigation("grades");
                });
#pragma warning restore 612, 618
        }
    }
}
